{% set name = "sif-parser" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sif_parser-{{ version }}.tar.gz
  sha256: 2d48d4df74222de1024d30574cac4a84174a204268ad47ca28d453baf75e6373

build:
  entry_points:
    - sif_parser=sif_parser.__main__:_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.10
    - pandas
    - pillow
    - python >=3.6

test:
  imports:
    - sif_parser
  commands:
    - pip list
    - pip check
    - sif_parser --help
  requires:
    - pip

about:
  home: https://github.com/fujiisoup/sif_parser
  summary: Python package to read Andor sif file.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fujiisoup
    - goanpeca
